meta_product_name: "Piggy Baku"
meta_title: "Piggy Baku - Secret bank for sensitive people"
meta_description: "PiggyBaku is a secret diary for sensitive people. It helps to rationalise your irrational feelings and get over those stubborn thoughts. Track your daily feelings-balance, take a step towards becoming a happier person!"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@piggybaku"   # required for Twitter Cards
